// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: new_cell_masks.proto
// Protobuf C++ Version: 6.33.4

#include "new_cell_masks.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace histotyper_v2 {

inline constexpr TileSegmentationData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cells_blob_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tissue_blob_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        x_{0u},
        y_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR TileSegmentationData::TileSegmentationData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TileSegmentationData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TileSegmentationDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TileSegmentationDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TileSegmentationDataDefaultTypeInternal() {}
  union {
    TileSegmentationData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TileSegmentationDataDefaultTypeInternal _TileSegmentationData_default_instance_;

inline constexpr SlideSegmentationData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cell_class_names_{},
        tissue_class_names_{},
        tiles_{},
        slide_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        slide_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cell_model_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tissue_model_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        mpp_{0},
        max_level_{0u},
        level_{0u},
        tile_size_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR SlideSegmentationData::SlideSegmentationData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SlideSegmentationData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SlideSegmentationDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SlideSegmentationDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SlideSegmentationDataDefaultTypeInternal() {}
  union {
    SlideSegmentationData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SlideSegmentationDataDefaultTypeInternal _SlideSegmentationData_default_instance_;
}  // namespace histotyper_v2
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_new_5fcell_5fmasks_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_new_5fcell_5fmasks_2eproto = nullptr;
const ::uint32_t
    TableStruct_new_5fcell_5fmasks_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::TileSegmentationData, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::TileSegmentationData, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::TileSegmentationData, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::TileSegmentationData, _impl_.cells_blob_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::TileSegmentationData, _impl_.tissue_blob_),
        2,
        3,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_._has_bits_),
        14, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.slide_id_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.slide_path_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.mpp_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.max_level_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.tile_size_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.cell_model_name_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.tissue_model_name_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.cell_class_names_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.tissue_class_names_),
        PROTOBUF_FIELD_OFFSET(::histotyper_v2::SlideSegmentationData, _impl_.tiles_),
        3,
        4,
        7,
        8,
        9,
        10,
        5,
        6,
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::histotyper_v2::TileSegmentationData)},
        {11, sizeof(::histotyper_v2::SlideSegmentationData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::histotyper_v2::_TileSegmentationData_default_instance_._instance,
    &::histotyper_v2::_SlideSegmentationData_default_instance_._instance,
};
const char descriptor_table_protodef_new_5fcell_5fmasks_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024new_cell_masks.proto\022\rhistotyper_v2\"U\n"
    "\024TileSegmentationData\022\t\n\001x\030\001 \001(\r\022\t\n\001y\030\002 "
    "\001(\r\022\022\n\ncells_blob\030\003 \001(\014\022\023\n\013tissue_blob\030\004"
    " \001(\014\"\235\002\n\025SlideSegmentationData\022\020\n\010slide_"
    "id\030\001 \001(\t\022\022\n\nslide_path\030\002 \001(\t\022\013\n\003mpp\030\003 \001("
    "\002\022\021\n\tmax_level\030\004 \001(\r\022\r\n\005level\030\005 \001(\r\022\021\n\tt"
    "ile_size\030\006 \001(\r\022\027\n\017cell_model_name\030\007 \001(\t\022"
    "\031\n\021tissue_model_name\030\010 \001(\t\022\030\n\020cell_class"
    "_names\030\t \003(\t\022\032\n\022tissue_class_names\030\n \003(\t"
    "\0222\n\005tiles\030\013 \003(\0132#.histotyper_v2.TileSegm"
    "entationDatab\006proto3"
};
static ::absl::once_flag descriptor_table_new_5fcell_5fmasks_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_new_5fcell_5fmasks_2eproto = {
    false,
    false,
    420,
    descriptor_table_protodef_new_5fcell_5fmasks_2eproto,
    "new_cell_masks.proto",
    &descriptor_table_new_5fcell_5fmasks_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_new_5fcell_5fmasks_2eproto::offsets,
    file_level_enum_descriptors_new_5fcell_5fmasks_2eproto,
    file_level_service_descriptors_new_5fcell_5fmasks_2eproto,
};
namespace histotyper_v2 {
// ===================================================================

class TileSegmentationData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TileSegmentationData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_._has_bits_);
};

TileSegmentationData::TileSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TileSegmentationData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:histotyper_v2.TileSegmentationData)
}
PROTOBUF_NDEBUG_INLINE TileSegmentationData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::histotyper_v2::TileSegmentationData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        cells_blob_(arena, from.cells_blob_),
        tissue_blob_(arena, from.tissue_blob_) {}

TileSegmentationData::TileSegmentationData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TileSegmentationData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TileSegmentationData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TileSegmentationData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, x_),
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));

  // @@protoc_insertion_point(copy_constructor:histotyper_v2.TileSegmentationData)
}
PROTOBUF_NDEBUG_INLINE TileSegmentationData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        cells_blob_(arena),
        tissue_blob_(arena) {}

inline void TileSegmentationData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));
}
TileSegmentationData::~TileSegmentationData() {
  // @@protoc_insertion_point(destructor:histotyper_v2.TileSegmentationData)
  SharedDtor(*this);
}
inline void TileSegmentationData::SharedDtor(MessageLite& self) {
  TileSegmentationData& this_ = static_cast<TileSegmentationData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cells_blob_.Destroy();
  this_._impl_.tissue_blob_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TileSegmentationData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TileSegmentationData(arena);
}
constexpr auto TileSegmentationData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TileSegmentationData),
                                            alignof(TileSegmentationData));
}
constexpr auto TileSegmentationData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TileSegmentationData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &TileSegmentationData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TileSegmentationData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TileSegmentationData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TileSegmentationData>(), &TileSegmentationData::ByteSizeLong,
              &TileSegmentationData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_._cached_size_),
          false,
      },
      &TileSegmentationData::kDescriptorMethods,
      &descriptor_table_new_5fcell_5fmasks_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TileSegmentationData_class_data_ =
        TileSegmentationData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TileSegmentationData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TileSegmentationData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TileSegmentationData_class_data_.tc_table);
  return TileSegmentationData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
TileSegmentationData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TileSegmentationData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::histotyper_v2::TileSegmentationData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes tissue_blob = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.tissue_blob_)}},
    // uint32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TileSegmentationData, _impl_.x_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.x_)}},
    // uint32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TileSegmentationData, _impl_.y_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.y_)}},
    // bytes cells_blob = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.cells_blob_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 x = 1;
    {PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.x_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 y = 2;
    {PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.y_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes cells_blob = 3;
    {PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.cells_blob_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes tissue_blob = 4;
    {PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.tissue_blob_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TileSegmentationData::Clear() {
// @@protoc_insertion_point(message_clear_start:histotyper_v2.TileSegmentationData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.cells_blob_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.tissue_blob_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.y_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TileSegmentationData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TileSegmentationData& this_ = static_cast<const TileSegmentationData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TileSegmentationData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TileSegmentationData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:histotyper_v2.TileSegmentationData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_x() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_x(), target);
    }
  }

  // uint32 y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_y() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_y(), target);
    }
  }

  // bytes cells_blob = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_cells_blob().empty()) {
      const ::std::string& _s = this_._internal_cells_blob();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bytes tissue_blob = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_tissue_blob().empty()) {
      const ::std::string& _s = this_._internal_tissue_blob();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:histotyper_v2.TileSegmentationData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TileSegmentationData::ByteSizeLong(const MessageLite& base) {
  const TileSegmentationData& this_ = static_cast<const TileSegmentationData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TileSegmentationData::ByteSizeLong() const {
  const TileSegmentationData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:histotyper_v2.TileSegmentationData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // bytes cells_blob = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_cells_blob().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_cells_blob());
      }
    }
    // bytes tissue_blob = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_tissue_blob().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_tissue_blob());
      }
    }
    // uint32 x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_x() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_x());
      }
    }
    // uint32 y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_y() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_y());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TileSegmentationData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TileSegmentationData*>(&to_msg);
  auto& from = static_cast<const TileSegmentationData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:histotyper_v2.TileSegmentationData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_cells_blob().empty()) {
        _this->_internal_set_cells_blob(from._internal_cells_blob());
      } else {
        if (_this->_impl_.cells_blob_.IsDefault()) {
          _this->_internal_set_cells_blob("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_tissue_blob().empty()) {
        _this->_internal_set_tissue_blob(from._internal_tissue_blob());
      } else {
        if (_this->_impl_.tissue_blob_.IsDefault()) {
          _this->_internal_set_tissue_blob("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_x() != 0) {
        _this->_impl_.x_ = from._impl_.x_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_y() != 0) {
        _this->_impl_.y_ = from._impl_.y_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TileSegmentationData::CopyFrom(const TileSegmentationData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:histotyper_v2.TileSegmentationData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TileSegmentationData::InternalSwap(TileSegmentationData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cells_blob_, &other->_impl_.cells_blob_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tissue_blob_, &other->_impl_.tissue_blob_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.y_)
      + sizeof(TileSegmentationData::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(TileSegmentationData, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata TileSegmentationData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SlideSegmentationData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SlideSegmentationData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_._has_bits_);
};

SlideSegmentationData::SlideSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SlideSegmentationData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:histotyper_v2.SlideSegmentationData)
}
PROTOBUF_NDEBUG_INLINE SlideSegmentationData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::histotyper_v2::SlideSegmentationData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        cell_class_names_{visibility, arena, from.cell_class_names_},
        tissue_class_names_{visibility, arena, from.tissue_class_names_},
        tiles_{visibility, arena, from.tiles_},
        slide_id_(arena, from.slide_id_),
        slide_path_(arena, from.slide_path_),
        cell_model_name_(arena, from.cell_model_name_),
        tissue_model_name_(arena, from.tissue_model_name_) {}

SlideSegmentationData::SlideSegmentationData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SlideSegmentationData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SlideSegmentationData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SlideSegmentationData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, mpp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, mpp_),
           offsetof(Impl_, tile_size_) -
               offsetof(Impl_, mpp_) +
               sizeof(Impl_::tile_size_));

  // @@protoc_insertion_point(copy_constructor:histotyper_v2.SlideSegmentationData)
}
PROTOBUF_NDEBUG_INLINE SlideSegmentationData::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        cell_class_names_{visibility, arena},
        tissue_class_names_{visibility, arena},
        tiles_{visibility, arena},
        slide_id_(arena),
        slide_path_(arena),
        cell_model_name_(arena),
        tissue_model_name_(arena) {}

inline void SlideSegmentationData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, mpp_),
           0,
           offsetof(Impl_, tile_size_) -
               offsetof(Impl_, mpp_) +
               sizeof(Impl_::tile_size_));
}
SlideSegmentationData::~SlideSegmentationData() {
  // @@protoc_insertion_point(destructor:histotyper_v2.SlideSegmentationData)
  SharedDtor(*this);
}
inline void SlideSegmentationData::SharedDtor(MessageLite& self) {
  SlideSegmentationData& this_ = static_cast<SlideSegmentationData&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.slide_id_.Destroy();
  this_._impl_.slide_path_.Destroy();
  this_._impl_.cell_model_name_.Destroy();
  this_._impl_.tissue_model_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SlideSegmentationData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SlideSegmentationData(arena);
}
constexpr auto SlideSegmentationData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.cell_class_names_) +
          decltype(SlideSegmentationData::_impl_.cell_class_names_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tissue_class_names_) +
          decltype(SlideSegmentationData::_impl_.tissue_class_names_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tiles_) +
          decltype(SlideSegmentationData::_impl_.tiles_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SlideSegmentationData), alignof(SlideSegmentationData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SlideSegmentationData::PlacementNew_,
                                 sizeof(SlideSegmentationData),
                                 alignof(SlideSegmentationData));
  }
}
constexpr auto SlideSegmentationData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SlideSegmentationData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SlideSegmentationData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SlideSegmentationData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SlideSegmentationData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SlideSegmentationData>(), &SlideSegmentationData::ByteSizeLong,
              &SlideSegmentationData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_._cached_size_),
          false,
      },
      &SlideSegmentationData::kDescriptorMethods,
      &descriptor_table_new_5fcell_5fmasks_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SlideSegmentationData_class_data_ =
        SlideSegmentationData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SlideSegmentationData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SlideSegmentationData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SlideSegmentationData_class_data_.tc_table);
  return SlideSegmentationData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 1, 136, 2>
SlideSegmentationData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SlideSegmentationData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::histotyper_v2::SlideSegmentationData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string slide_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.slide_id_)}},
    // string slide_path = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 4, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.slide_path_)}},
    // float mpp = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 7, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.mpp_)}},
    // uint32 max_level = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SlideSegmentationData, _impl_.max_level_), 8>(),
     {32, 8, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.max_level_)}},
    // uint32 level = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SlideSegmentationData, _impl_.level_), 9>(),
     {40, 9, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.level_)}},
    // uint32 tile_size = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SlideSegmentationData, _impl_.tile_size_), 10>(),
     {48, 10, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tile_size_)}},
    // string cell_model_name = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 5, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.cell_model_name_)}},
    // string tissue_model_name = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 6, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tissue_model_name_)}},
    // repeated string cell_class_names = 9;
    {::_pbi::TcParser::FastUR1,
     {74, 0, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.cell_class_names_)}},
    // repeated string tissue_class_names = 10;
    {::_pbi::TcParser::FastUR1,
     {82, 1, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tissue_class_names_)}},
    // repeated .histotyper_v2.TileSegmentationData tiles = 11;
    {::_pbi::TcParser::FastMtR1,
     {90, 2, 0,
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tiles_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string slide_id = 1;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.slide_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string slide_path = 2;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.slide_path_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float mpp = 3;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.mpp_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // uint32 max_level = 4;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.max_level_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 level = 5;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.level_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 tile_size = 6;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tile_size_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string cell_model_name = 7;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.cell_model_name_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string tissue_model_name = 8;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tissue_model_name_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string cell_class_names = 9;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.cell_class_names_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string tissue_class_names = 10;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tissue_class_names_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated .histotyper_v2.TileSegmentationData tiles = 11;
    {PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tiles_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::histotyper_v2::TileSegmentationData>()},
  }},
  {{
    "\43\10\12\0\0\0\0\17\21\20\22\0\0\0\0\0"
    "histotyper_v2.SlideSegmentationData"
    "slide_id"
    "slide_path"
    "cell_model_name"
    "tissue_model_name"
    "cell_class_names"
    "tissue_class_names"
  }},
};
PROTOBUF_NOINLINE void SlideSegmentationData::Clear() {
// @@protoc_insertion_point(message_clear_start:histotyper_v2.SlideSegmentationData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.cell_class_names_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.tissue_class_names_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.tiles_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.slide_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.slide_path_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.cell_model_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _impl_.tissue_model_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.mpp_ = 0;
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    ::memset(&_impl_.max_level_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.tile_size_) -
        reinterpret_cast<char*>(&_impl_.max_level_)) + sizeof(_impl_.tile_size_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SlideSegmentationData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SlideSegmentationData& this_ = static_cast<const SlideSegmentationData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SlideSegmentationData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SlideSegmentationData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:histotyper_v2.SlideSegmentationData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string slide_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_slide_id().empty()) {
      const ::std::string& _s = this_._internal_slide_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.slide_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string slide_path = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_slide_path().empty()) {
      const ::std::string& _s = this_._internal_slide_path();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.slide_path");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // float mpp = 3;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_mpp()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_mpp(), target);
    }
  }

  // uint32 max_level = 4;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_max_level() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_max_level(), target);
    }
  }

  // uint32 level = 5;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_level() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_level(), target);
    }
  }

  // uint32 tile_size = 6;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_tile_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_tile_size(), target);
    }
  }

  // string cell_model_name = 7;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_cell_model_name().empty()) {
      const ::std::string& _s = this_._internal_cell_model_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.cell_model_name");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string tissue_model_name = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_tissue_model_name().empty()) {
      const ::std::string& _s = this_._internal_tissue_model_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.tissue_model_name");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  // repeated string cell_class_names = 9;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_cell_class_names_size(); i < n; ++i) {
      const auto& s = this_._internal_cell_class_names().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.cell_class_names");
      target = stream->WriteString(9, s, target);
    }
  }

  // repeated string tissue_class_names = 10;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_tissue_class_names_size(); i < n; ++i) {
      const auto& s = this_._internal_tissue_class_names().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "histotyper_v2.SlideSegmentationData.tissue_class_names");
      target = stream->WriteString(10, s, target);
    }
  }

  // repeated .histotyper_v2.TileSegmentationData tiles = 11;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_tiles_size());
         i < n; i++) {
      const auto& repfield = this_._internal_tiles().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              11, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:histotyper_v2.SlideSegmentationData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SlideSegmentationData::ByteSizeLong(const MessageLite& base) {
  const SlideSegmentationData& this_ = static_cast<const SlideSegmentationData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SlideSegmentationData::ByteSizeLong() const {
  const SlideSegmentationData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:histotyper_v2.SlideSegmentationData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated string cell_class_names = 9;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_cell_class_names().size());
      for (int i = 0, n = this_._internal_cell_class_names().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_cell_class_names().Get(i));
      }
    }
    // repeated string tissue_class_names = 10;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_tissue_class_names().size());
      for (int i = 0, n = this_._internal_tissue_class_names().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_tissue_class_names().Get(i));
      }
    }
    // repeated .histotyper_v2.TileSegmentationData tiles = 11;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_tiles_size();
      for (const auto& msg : this_._internal_tiles()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string slide_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_slide_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_slide_id());
      }
    }
    // string slide_path = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_slide_path().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_slide_path());
      }
    }
    // string cell_model_name = 7;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_cell_model_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_cell_model_name());
      }
    }
    // string tissue_model_name = 8;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!this_._internal_tissue_model_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_tissue_model_name());
      }
    }
    // float mpp = 3;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_mpp()) != 0) {
        total_size += 5;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    // uint32 max_level = 4;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_max_level() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_max_level());
      }
    }
    // uint32 level = 5;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_level() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_level());
      }
    }
    // uint32 tile_size = 6;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_tile_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_tile_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SlideSegmentationData::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SlideSegmentationData*>(&to_msg);
  auto& from = static_cast<const SlideSegmentationData&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:histotyper_v2.SlideSegmentationData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_cell_class_names()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_cell_class_names());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_tissue_class_names()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_tissue_class_names());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_tiles()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_tiles());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_slide_id().empty()) {
        _this->_internal_set_slide_id(from._internal_slide_id());
      } else {
        if (_this->_impl_.slide_id_.IsDefault()) {
          _this->_internal_set_slide_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_slide_path().empty()) {
        _this->_internal_set_slide_path(from._internal_slide_path());
      } else {
        if (_this->_impl_.slide_path_.IsDefault()) {
          _this->_internal_set_slide_path("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_cell_model_name().empty()) {
        _this->_internal_set_cell_model_name(from._internal_cell_model_name());
      } else {
        if (_this->_impl_.cell_model_name_.IsDefault()) {
          _this->_internal_set_cell_model_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!from._internal_tissue_model_name().empty()) {
        _this->_internal_set_tissue_model_name(from._internal_tissue_model_name());
      } else {
        if (_this->_impl_.tissue_model_name_.IsDefault()) {
          _this->_internal_set_tissue_model_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_mpp()) != 0) {
        _this->_impl_.mpp_ = from._impl_.mpp_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_max_level() != 0) {
        _this->_impl_.max_level_ = from._impl_.max_level_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_level() != 0) {
        _this->_impl_.level_ = from._impl_.level_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_tile_size() != 0) {
        _this->_impl_.tile_size_ = from._impl_.tile_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SlideSegmentationData::CopyFrom(const SlideSegmentationData& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:histotyper_v2.SlideSegmentationData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SlideSegmentationData::InternalSwap(SlideSegmentationData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.cell_class_names_.InternalSwap(&other->_impl_.cell_class_names_);
  _impl_.tissue_class_names_.InternalSwap(&other->_impl_.tissue_class_names_);
  _impl_.tiles_.InternalSwap(&other->_impl_.tiles_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.slide_id_, &other->_impl_.slide_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.slide_path_, &other->_impl_.slide_path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cell_model_name_, &other->_impl_.cell_model_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tissue_model_name_, &other->_impl_.tissue_model_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.tile_size_)
      + sizeof(SlideSegmentationData::_impl_.tile_size_)
      - PROTOBUF_FIELD_OFFSET(SlideSegmentationData, _impl_.mpp_)>(
          reinterpret_cast<char*>(&_impl_.mpp_),
          reinterpret_cast<char*>(&other->_impl_.mpp_));
}

::google::protobuf::Metadata SlideSegmentationData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace histotyper_v2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_new_5fcell_5fmasks_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
