// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: new_cell_masks.proto
// Protobuf C++ Version: 6.33.4

#ifndef new_5fcell_5fmasks_2eproto_2epb_2eh
#define new_5fcell_5fmasks_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_new_5fcell_5fmasks_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_new_5fcell_5fmasks_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_new_5fcell_5fmasks_2eproto;
}  // extern "C"
namespace histotyper_v2 {
class SlideSegmentationData;
struct SlideSegmentationDataDefaultTypeInternal;
extern SlideSegmentationDataDefaultTypeInternal _SlideSegmentationData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SlideSegmentationData_class_data_;
class TileSegmentationData;
struct TileSegmentationDataDefaultTypeInternal;
extern TileSegmentationDataDefaultTypeInternal _TileSegmentationData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TileSegmentationData_class_data_;
}  // namespace histotyper_v2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace histotyper_v2 {

// ===================================================================


// -------------------------------------------------------------------

class TileSegmentationData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:histotyper_v2.TileSegmentationData) */ {
 public:
  inline TileSegmentationData() : TileSegmentationData(nullptr) {}
  ~TileSegmentationData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TileSegmentationData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TileSegmentationData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TileSegmentationData(::google::protobuf::internal::ConstantInitialized);

  inline TileSegmentationData(const TileSegmentationData& from) : TileSegmentationData(nullptr, from) {}
  inline TileSegmentationData(TileSegmentationData&& from) noexcept
      : TileSegmentationData(nullptr, ::std::move(from)) {}
  inline TileSegmentationData& operator=(const TileSegmentationData& from) {
    CopyFrom(from);
    return *this;
  }
  inline TileSegmentationData& operator=(TileSegmentationData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TileSegmentationData& default_instance() {
    return *reinterpret_cast<const TileSegmentationData*>(
        &_TileSegmentationData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TileSegmentationData& a, TileSegmentationData& b) { a.Swap(&b); }
  inline void Swap(TileSegmentationData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TileSegmentationData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TileSegmentationData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TileSegmentationData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TileSegmentationData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TileSegmentationData& from) { TileSegmentationData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TileSegmentationData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "histotyper_v2.TileSegmentationData"; }

  explicit TileSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TileSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TileSegmentationData& from);
  TileSegmentationData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TileSegmentationData&& from) noexcept
      : TileSegmentationData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCellsBlobFieldNumber = 3,
    kTissueBlobFieldNumber = 4,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // bytes cells_blob = 3;
  void clear_cells_blob() ;
  const ::std::string& cells_blob() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cells_blob(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cells_blob();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cells_blob();
  void set_allocated_cells_blob(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cells_blob() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cells_blob(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cells_blob();

  public:
  // bytes tissue_blob = 4;
  void clear_tissue_blob() ;
  const ::std::string& tissue_blob() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tissue_blob(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tissue_blob();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tissue_blob();
  void set_allocated_tissue_blob(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tissue_blob() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tissue_blob(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tissue_blob();

  public:
  // uint32 x = 1;
  void clear_x() ;
  ::uint32_t x() const;
  void set_x(::uint32_t value);

  private:
  ::uint32_t _internal_x() const;
  void _internal_set_x(::uint32_t value);

  public:
  // uint32 y = 2;
  void clear_y() ;
  ::uint32_t y() const;
  void set_y(::uint32_t value);

  private:
  ::uint32_t _internal_y() const;
  void _internal_set_y(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:histotyper_v2.TileSegmentationData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TileSegmentationData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cells_blob_;
    ::google::protobuf::internal::ArenaStringPtr tissue_blob_;
    ::uint32_t x_;
    ::uint32_t y_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_new_5fcell_5fmasks_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TileSegmentationData_class_data_;
// -------------------------------------------------------------------

class SlideSegmentationData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:histotyper_v2.SlideSegmentationData) */ {
 public:
  inline SlideSegmentationData() : SlideSegmentationData(nullptr) {}
  ~SlideSegmentationData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SlideSegmentationData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SlideSegmentationData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SlideSegmentationData(::google::protobuf::internal::ConstantInitialized);

  inline SlideSegmentationData(const SlideSegmentationData& from) : SlideSegmentationData(nullptr, from) {}
  inline SlideSegmentationData(SlideSegmentationData&& from) noexcept
      : SlideSegmentationData(nullptr, ::std::move(from)) {}
  inline SlideSegmentationData& operator=(const SlideSegmentationData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SlideSegmentationData& operator=(SlideSegmentationData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SlideSegmentationData& default_instance() {
    return *reinterpret_cast<const SlideSegmentationData*>(
        &_SlideSegmentationData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SlideSegmentationData& a, SlideSegmentationData& b) { a.Swap(&b); }
  inline void Swap(SlideSegmentationData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SlideSegmentationData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SlideSegmentationData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SlideSegmentationData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SlideSegmentationData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SlideSegmentationData& from) { SlideSegmentationData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SlideSegmentationData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "histotyper_v2.SlideSegmentationData"; }

  explicit SlideSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SlideSegmentationData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SlideSegmentationData& from);
  SlideSegmentationData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SlideSegmentationData&& from) noexcept
      : SlideSegmentationData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCellClassNamesFieldNumber = 9,
    kTissueClassNamesFieldNumber = 10,
    kTilesFieldNumber = 11,
    kSlideIdFieldNumber = 1,
    kSlidePathFieldNumber = 2,
    kCellModelNameFieldNumber = 7,
    kTissueModelNameFieldNumber = 8,
    kMppFieldNumber = 3,
    kMaxLevelFieldNumber = 4,
    kLevelFieldNumber = 5,
    kTileSizeFieldNumber = 6,
  };
  // repeated string cell_class_names = 9;
  int cell_class_names_size() const;
  private:
  int _internal_cell_class_names_size() const;

  public:
  void clear_cell_class_names() ;
  const ::std::string& cell_class_names(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_cell_class_names(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cell_class_names(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_cell_class_names();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_cell_class_names(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& cell_class_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_cell_class_names();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_cell_class_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_cell_class_names();

  public:
  // repeated string tissue_class_names = 10;
  int tissue_class_names_size() const;
  private:
  int _internal_tissue_class_names_size() const;

  public:
  void clear_tissue_class_names() ;
  const ::std::string& tissue_class_names(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_tissue_class_names(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tissue_class_names(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_tissue_class_names();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_tissue_class_names(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& tissue_class_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_tissue_class_names();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_tissue_class_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_tissue_class_names();

  public:
  // repeated .histotyper_v2.TileSegmentationData tiles = 11;
  int tiles_size() const;
  private:
  int _internal_tiles_size() const;

  public:
  void clear_tiles() ;
  ::histotyper_v2::TileSegmentationData* PROTOBUF_NONNULL mutable_tiles(int index);
  ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>* PROTOBUF_NONNULL mutable_tiles();

  private:
  const ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>& _internal_tiles() const;
  ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>* PROTOBUF_NONNULL _internal_mutable_tiles();
  public:
  const ::histotyper_v2::TileSegmentationData& tiles(int index) const;
  ::histotyper_v2::TileSegmentationData* PROTOBUF_NONNULL add_tiles();
  const ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>& tiles() const;
  // string slide_id = 1;
  void clear_slide_id() ;
  const ::std::string& slide_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_slide_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_slide_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_slide_id();
  void set_allocated_slide_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_slide_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_slide_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_slide_id();

  public:
  // string slide_path = 2;
  void clear_slide_path() ;
  const ::std::string& slide_path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_slide_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_slide_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_slide_path();
  void set_allocated_slide_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_slide_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_slide_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_slide_path();

  public:
  // string cell_model_name = 7;
  void clear_cell_model_name() ;
  const ::std::string& cell_model_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cell_model_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cell_model_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cell_model_name();
  void set_allocated_cell_model_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cell_model_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cell_model_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cell_model_name();

  public:
  // string tissue_model_name = 8;
  void clear_tissue_model_name() ;
  const ::std::string& tissue_model_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tissue_model_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tissue_model_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tissue_model_name();
  void set_allocated_tissue_model_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tissue_model_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tissue_model_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tissue_model_name();

  public:
  // float mpp = 3;
  void clear_mpp() ;
  float mpp() const;
  void set_mpp(float value);

  private:
  float _internal_mpp() const;
  void _internal_set_mpp(float value);

  public:
  // uint32 max_level = 4;
  void clear_max_level() ;
  ::uint32_t max_level() const;
  void set_max_level(::uint32_t value);

  private:
  ::uint32_t _internal_max_level() const;
  void _internal_set_max_level(::uint32_t value);

  public:
  // uint32 level = 5;
  void clear_level() ;
  ::uint32_t level() const;
  void set_level(::uint32_t value);

  private:
  ::uint32_t _internal_level() const;
  void _internal_set_level(::uint32_t value);

  public:
  // uint32 tile_size = 6;
  void clear_tile_size() ;
  ::uint32_t tile_size() const;
  void set_tile_size(::uint32_t value);

  private:
  ::uint32_t _internal_tile_size() const;
  void _internal_set_tile_size(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:histotyper_v2.SlideSegmentationData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 11,
                                   1, 136,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SlideSegmentationData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> cell_class_names_;
    ::google::protobuf::RepeatedPtrField<::std::string> tissue_class_names_;
    ::google::protobuf::RepeatedPtrField< ::histotyper_v2::TileSegmentationData > tiles_;
    ::google::protobuf::internal::ArenaStringPtr slide_id_;
    ::google::protobuf::internal::ArenaStringPtr slide_path_;
    ::google::protobuf::internal::ArenaStringPtr cell_model_name_;
    ::google::protobuf::internal::ArenaStringPtr tissue_model_name_;
    float mpp_;
    ::uint32_t max_level_;
    ::uint32_t level_;
    ::uint32_t tile_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_new_5fcell_5fmasks_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SlideSegmentationData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TileSegmentationData

// uint32 x = 1;
inline void TileSegmentationData::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t TileSegmentationData::x() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.TileSegmentationData.x)
  return _internal_x();
}
inline void TileSegmentationData::set_x(::uint32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:histotyper_v2.TileSegmentationData.x)
}
inline ::uint32_t TileSegmentationData::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void TileSegmentationData::_internal_set_x(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// uint32 y = 2;
inline void TileSegmentationData::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t TileSegmentationData::y() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.TileSegmentationData.y)
  return _internal_y();
}
inline void TileSegmentationData::set_y(::uint32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:histotyper_v2.TileSegmentationData.y)
}
inline ::uint32_t TileSegmentationData::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void TileSegmentationData::_internal_set_y(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// bytes cells_blob = 3;
inline void TileSegmentationData::clear_cells_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cells_blob_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& TileSegmentationData::cells_blob() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.TileSegmentationData.cells_blob)
  return _internal_cells_blob();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TileSegmentationData::set_cells_blob(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cells_blob_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.TileSegmentationData.cells_blob)
}
inline ::std::string* PROTOBUF_NONNULL TileSegmentationData::mutable_cells_blob()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cells_blob();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.TileSegmentationData.cells_blob)
  return _s;
}
inline const ::std::string& TileSegmentationData::_internal_cells_blob() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cells_blob_.Get();
}
inline void TileSegmentationData::_internal_set_cells_blob(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cells_blob_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TileSegmentationData::_internal_mutable_cells_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cells_blob_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TileSegmentationData::release_cells_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.TileSegmentationData.cells_blob)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cells_blob_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cells_blob_.Set("", GetArena());
  }
  return released;
}
inline void TileSegmentationData::set_allocated_cells_blob(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cells_blob_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cells_blob_.IsDefault()) {
    _impl_.cells_blob_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.TileSegmentationData.cells_blob)
}

// bytes tissue_blob = 4;
inline void TileSegmentationData::clear_tissue_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tissue_blob_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& TileSegmentationData::tissue_blob() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.TileSegmentationData.tissue_blob)
  return _internal_tissue_blob();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TileSegmentationData::set_tissue_blob(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.tissue_blob_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.TileSegmentationData.tissue_blob)
}
inline ::std::string* PROTOBUF_NONNULL TileSegmentationData::mutable_tissue_blob()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_tissue_blob();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.TileSegmentationData.tissue_blob)
  return _s;
}
inline const ::std::string& TileSegmentationData::_internal_tissue_blob() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tissue_blob_.Get();
}
inline void TileSegmentationData::_internal_set_tissue_blob(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tissue_blob_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TileSegmentationData::_internal_mutable_tissue_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tissue_blob_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TileSegmentationData::release_tissue_blob() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.TileSegmentationData.tissue_blob)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.tissue_blob_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tissue_blob_.Set("", GetArena());
  }
  return released;
}
inline void TileSegmentationData::set_allocated_tissue_blob(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.tissue_blob_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tissue_blob_.IsDefault()) {
    _impl_.tissue_blob_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.TileSegmentationData.tissue_blob)
}

// -------------------------------------------------------------------

// SlideSegmentationData

// string slide_id = 1;
inline void SlideSegmentationData::clear_slide_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slide_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& SlideSegmentationData::slide_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.slide_id)
  return _internal_slide_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SlideSegmentationData::set_slide_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.slide_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.slide_id)
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_slide_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_slide_id();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.slide_id)
  return _s;
}
inline const ::std::string& SlideSegmentationData::_internal_slide_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slide_id_.Get();
}
inline void SlideSegmentationData::_internal_set_slide_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slide_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::_internal_mutable_slide_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.slide_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SlideSegmentationData::release_slide_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.SlideSegmentationData.slide_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.slide_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.slide_id_.Set("", GetArena());
  }
  return released;
}
inline void SlideSegmentationData::set_allocated_slide_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.slide_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.slide_id_.IsDefault()) {
    _impl_.slide_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.SlideSegmentationData.slide_id)
}

// string slide_path = 2;
inline void SlideSegmentationData::clear_slide_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slide_path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& SlideSegmentationData::slide_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.slide_path)
  return _internal_slide_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SlideSegmentationData::set_slide_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.slide_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.slide_path)
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_slide_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_slide_path();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.slide_path)
  return _s;
}
inline const ::std::string& SlideSegmentationData::_internal_slide_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slide_path_.Get();
}
inline void SlideSegmentationData::_internal_set_slide_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slide_path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::_internal_mutable_slide_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.slide_path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SlideSegmentationData::release_slide_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.SlideSegmentationData.slide_path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.slide_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.slide_path_.Set("", GetArena());
  }
  return released;
}
inline void SlideSegmentationData::set_allocated_slide_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.slide_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.slide_path_.IsDefault()) {
    _impl_.slide_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.SlideSegmentationData.slide_path)
}

// float mpp = 3;
inline void SlideSegmentationData::clear_mpp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mpp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline float SlideSegmentationData::mpp() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.mpp)
  return _internal_mpp();
}
inline void SlideSegmentationData::set_mpp(float value) {
  _internal_set_mpp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.mpp)
}
inline float SlideSegmentationData::_internal_mpp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mpp_;
}
inline void SlideSegmentationData::_internal_set_mpp(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mpp_ = value;
}

// uint32 max_level = 4;
inline void SlideSegmentationData::clear_max_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_level_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint32_t SlideSegmentationData::max_level() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.max_level)
  return _internal_max_level();
}
inline void SlideSegmentationData::set_max_level(::uint32_t value) {
  _internal_set_max_level(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.max_level)
}
inline ::uint32_t SlideSegmentationData::_internal_max_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_level_;
}
inline void SlideSegmentationData::_internal_set_max_level(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_level_ = value;
}

// uint32 level = 5;
inline void SlideSegmentationData::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint32_t SlideSegmentationData::level() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.level)
  return _internal_level();
}
inline void SlideSegmentationData::set_level(::uint32_t value) {
  _internal_set_level(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.level)
}
inline ::uint32_t SlideSegmentationData::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void SlideSegmentationData::_internal_set_level(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// uint32 tile_size = 6;
inline void SlideSegmentationData::clear_tile_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tile_size_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::uint32_t SlideSegmentationData::tile_size() const {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.tile_size)
  return _internal_tile_size();
}
inline void SlideSegmentationData::set_tile_size(::uint32_t value) {
  _internal_set_tile_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.tile_size)
}
inline ::uint32_t SlideSegmentationData::_internal_tile_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tile_size_;
}
inline void SlideSegmentationData::_internal_set_tile_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tile_size_ = value;
}

// string cell_model_name = 7;
inline void SlideSegmentationData::clear_cell_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cell_model_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& SlideSegmentationData::cell_model_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.cell_model_name)
  return _internal_cell_model_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SlideSegmentationData::set_cell_model_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.cell_model_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.cell_model_name)
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_cell_model_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_cell_model_name();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.cell_model_name)
  return _s;
}
inline const ::std::string& SlideSegmentationData::_internal_cell_model_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cell_model_name_.Get();
}
inline void SlideSegmentationData::_internal_set_cell_model_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cell_model_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::_internal_mutable_cell_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cell_model_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SlideSegmentationData::release_cell_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.SlideSegmentationData.cell_model_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.cell_model_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cell_model_name_.Set("", GetArena());
  }
  return released;
}
inline void SlideSegmentationData::set_allocated_cell_model_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.cell_model_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cell_model_name_.IsDefault()) {
    _impl_.cell_model_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.SlideSegmentationData.cell_model_name)
}

// string tissue_model_name = 8;
inline void SlideSegmentationData::clear_tissue_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tissue_model_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::std::string& SlideSegmentationData::tissue_model_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.tissue_model_name)
  return _internal_tissue_model_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SlideSegmentationData::set_tissue_model_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.tissue_model_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.tissue_model_name)
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_tissue_model_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::std::string* _s = _internal_mutable_tissue_model_name();
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.tissue_model_name)
  return _s;
}
inline const ::std::string& SlideSegmentationData::_internal_tissue_model_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tissue_model_name_.Get();
}
inline void SlideSegmentationData::_internal_set_tissue_model_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tissue_model_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::_internal_mutable_tissue_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tissue_model_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SlideSegmentationData::release_tissue_model_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:histotyper_v2.SlideSegmentationData.tissue_model_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000040U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  auto* released = _impl_.tissue_model_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tissue_model_name_.Set("", GetArena());
  }
  return released;
}
inline void SlideSegmentationData::set_allocated_tissue_model_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  _impl_.tissue_model_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tissue_model_name_.IsDefault()) {
    _impl_.tissue_model_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:histotyper_v2.SlideSegmentationData.tissue_model_name)
}

// repeated string cell_class_names = 9;
inline int SlideSegmentationData::_internal_cell_class_names_size() const {
  return _internal_cell_class_names().size();
}
inline int SlideSegmentationData::cell_class_names_size() const {
  return _internal_cell_class_names_size();
}
inline void SlideSegmentationData::clear_cell_class_names() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cell_class_names_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::add_cell_class_names()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_cell_class_names()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:histotyper_v2.SlideSegmentationData.cell_class_names)
  return _s;
}
inline const ::std::string& SlideSegmentationData::cell_class_names(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.cell_class_names)
  return _internal_cell_class_names().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_cell_class_names(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.cell_class_names)
  return _internal_mutable_cell_class_names()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SlideSegmentationData::set_cell_class_names(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_cell_class_names()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.cell_class_names)
}
template <typename Arg_, typename... Args_>
inline void SlideSegmentationData::add_cell_class_names(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_cell_class_names(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:histotyper_v2.SlideSegmentationData.cell_class_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& SlideSegmentationData::cell_class_names()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:histotyper_v2.SlideSegmentationData.cell_class_names)
  return _internal_cell_class_names();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SlideSegmentationData::mutable_cell_class_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:histotyper_v2.SlideSegmentationData.cell_class_names)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cell_class_names();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
SlideSegmentationData::_internal_cell_class_names() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cell_class_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SlideSegmentationData::_internal_mutable_cell_class_names() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cell_class_names_;
}

// repeated string tissue_class_names = 10;
inline int SlideSegmentationData::_internal_tissue_class_names_size() const {
  return _internal_tissue_class_names().size();
}
inline int SlideSegmentationData::tissue_class_names_size() const {
  return _internal_tissue_class_names_size();
}
inline void SlideSegmentationData::clear_tissue_class_names() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tissue_class_names_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::add_tissue_class_names()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_tissue_class_names()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:histotyper_v2.SlideSegmentationData.tissue_class_names)
  return _s;
}
inline const ::std::string& SlideSegmentationData::tissue_class_names(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.tissue_class_names)
  return _internal_tissue_class_names().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL SlideSegmentationData::mutable_tissue_class_names(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.tissue_class_names)
  return _internal_mutable_tissue_class_names()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SlideSegmentationData::set_tissue_class_names(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_tissue_class_names()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:histotyper_v2.SlideSegmentationData.tissue_class_names)
}
template <typename Arg_, typename... Args_>
inline void SlideSegmentationData::add_tissue_class_names(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_tissue_class_names(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:histotyper_v2.SlideSegmentationData.tissue_class_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& SlideSegmentationData::tissue_class_names()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:histotyper_v2.SlideSegmentationData.tissue_class_names)
  return _internal_tissue_class_names();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SlideSegmentationData::mutable_tissue_class_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:histotyper_v2.SlideSegmentationData.tissue_class_names)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tissue_class_names();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
SlideSegmentationData::_internal_tissue_class_names() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tissue_class_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
SlideSegmentationData::_internal_mutable_tissue_class_names() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tissue_class_names_;
}

// repeated .histotyper_v2.TileSegmentationData tiles = 11;
inline int SlideSegmentationData::_internal_tiles_size() const {
  return _internal_tiles().size();
}
inline int SlideSegmentationData::tiles_size() const {
  return _internal_tiles_size();
}
inline void SlideSegmentationData::clear_tiles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tiles_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::histotyper_v2::TileSegmentationData* PROTOBUF_NONNULL SlideSegmentationData::mutable_tiles(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:histotyper_v2.SlideSegmentationData.tiles)
  return _internal_mutable_tiles()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>* PROTOBUF_NONNULL SlideSegmentationData::mutable_tiles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:histotyper_v2.SlideSegmentationData.tiles)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tiles();
}
inline const ::histotyper_v2::TileSegmentationData& SlideSegmentationData::tiles(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:histotyper_v2.SlideSegmentationData.tiles)
  return _internal_tiles().Get(index);
}
inline ::histotyper_v2::TileSegmentationData* PROTOBUF_NONNULL SlideSegmentationData::add_tiles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::histotyper_v2::TileSegmentationData* _add =
      _internal_mutable_tiles()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:histotyper_v2.SlideSegmentationData.tiles)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>& SlideSegmentationData::tiles() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:histotyper_v2.SlideSegmentationData.tiles)
  return _internal_tiles();
}
inline const ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>&
SlideSegmentationData::_internal_tiles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tiles_;
}
inline ::google::protobuf::RepeatedPtrField<::histotyper_v2::TileSegmentationData>* PROTOBUF_NONNULL
SlideSegmentationData::_internal_mutable_tiles() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tiles_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace histotyper_v2


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // new_5fcell_5fmasks_2eproto_2epb_2eh
